### ISSUE TITLE
build_artefacts permission denied error in circleci build?

### ISSUE THREAD

**Issue by irmen** [conda-forge/serpent-feedstock#10]
@jakirkham , @whart222,
Trying to build a new version of serpent but the circleci build keeps failing with "WARNING:conda_build.build:failed to create env, retrying.  exception was: [Errno 13] Permission denied: '/feedstock_root/build_artefacts'" 
I don't know how to solve this?

**Comment by jakirkham** [comment]
I'm not seeing a PR. Is there one?

**Comment by irmen** [comment]
This is the one:  https://github.com/conda-forge/serpent-feedstock/pull/9

(I have merged it already, which is my mistake - should have noticed before doing that, that the circleci build was failing. )

The failing builds can be seen here https://circleci.com/gh/conda-forge/serpent-feedstock

**Comment by irmen** [comment]
Well, resolved by using conda smity rerender and merging those changes...
