### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by irmen** [conda-forge/serpent-feedstock#2]
getting this error (win 7, anaconda python 3.5):

```
C:\Users\irmen>conda install serpent
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 334, in install
    update_deps=args.update_deps)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 407, in install_actions
    add_defaults_to_specs(r, linked, specs)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 351, in add_defaults_to_specs
    for spec in specs
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 352, in <genexpr>
    for fn in r.find_matches(spec)
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 559, in find_matches
    res = self.find_matches_[ms] = list(self.find_matches_group(ms, self.groups))
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 549, in find_matches_group
    if ms.match_fast(rec['version'], rec['build']):
KeyError: 'build'
```

output of conda info:

```
C:\Users\irmen>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-32
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/win-32/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\irmen\.condarc
    is foreign system : True
```

**Comment by pelson** [comment]
Extremely curious. By modifying `"C:\Anaconda3\lib\site-packages\conda\resolve.py", line 549` are you able to let us know what `rec` contains?

**Comment by irmen** [comment]
Nevermind, the issue resolved itself after finally being able to run a succesful "conda upgrade conda" so that it is now version 4.0.6.

It's not been smooth sailing though to reach this:
- initially during the setup, it failed to register the menus, paths, and directories. I had to manually run the _nsys.py steps.
- after that, it refused to start because it couldn't deal with an entry in my PATH environment variable. I had to remove the path to the msdeploy utility inside the IIS folder to get conda to work from the start menu link.
- after that, it still complained that there wasn't an environment installed in c:\anaconda3 (which is its own install folder...)
- I forgot what I did exactly but most complaints and errors have disappeared after the conda upgrade command
- it did reinstall python 3.5 when installing serpent even though it was already installed. 

All in all, I'm not confident I have a fully correctly configured anaconda on the VM at the moment but am at a loss what to do to fix this or what might be wrong with how I ran the installer.

**Comment by pelson** [comment]
Sounds like anaconda teething issues. I'll ping @csoja who I believe is the product owner of Anaconda.

Feel free to continue the discussion in this issue - I'm going to unsubscribe (feel free to ping me with `@pelson` if you want me to see any of the discussion) and will close the issue as it doesn't sound like a serpernt-feedstock issue per-se.

Thanks for the helpful information @irmen.
