### ISSUE TITLE
how to add linux-32 bits package?

### ISSUE THREAD

**Issue by irmen** [conda-forge/serpent-feedstock#7]
@Juanlu001  @whart222 
How does one create a linux-64 and a linux-32 bits package as well? Currently only the 64 bits one is created.

**Comment by astrojuanlu** [comment]
No idea :/ Is it at all possible? Perhaps the CI services don't even support it...

**Comment by irmen** [comment]
I don't know... but as anaconda is available for both architectures I would assume packages can be made for both.

**Comment by astrojuanlu** [comment]
One can create Anaconda packages for 32bit Linux, but I'm not sure the automated conda-forge process supports it.

cc @jakirkham

**Comment by jakirkham** [comment]
It's not currently supported. Please see issue ( https://github.com/conda-forge/conda-forge.github.io/issues/163 ) for some discussion on supporting Linux 32-bit builds in conda-forge.

**Comment by irmen** [comment]
Thanks for the clarification. 32-bit linux users could always pip install serpent I suppose.
